enum HTTP_STATUS {
	// Successful Responses
	OK = 200,
	CREATED = 201,
	NO_CONTENT = 204,

	// Client Error Responses
	BAD_REQUEST = 400,
	UNAUTHORIZED = 401,
	FORBIDDEN = 403,
	NOT_FOUND = 404,
	CONFLICT = 409,
	UNPROCESSABLE_CONTENT = 422,
	TOO_MANY_REQUESTS = 429,

	// Server Error Responses
	INTERNAL_SERVER_ERROR = 500,
	SERVICE_UNAVAILABLE = 503
}

export default HTTP_STATUS;
